<?php

namespace UserBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUser($string) {
        
       // Récupération du gestionnaire d'entité
       $gestionnaireEntite = $this->_em;

        $nbMots = str_word_count($string);

        if ($nbMots == 1)
        {
            $requete = $gestionnaireEntite->createQuery('SELECT u FROM UserBundle:User u WHERE u.nom = :string OR u.prenom = :string');
            $requete->setParameter('string', $string);
        }
        else
        {
            $tabMots = explode(" ", $string);
            $requete = $gestionnaireEntite->createQuery('SELECT u FROM UserBundle:User u WHERE u.nom = :nom OR u.nom = :prenom OR u.prenom = :nom OR u.prenom = :prenom');
            $requete->setParameter('nom', $tabMots[0]);
            $requete->setParameter('prenom', $tabMots[1]);
        }
    
        $tabUser = $requete->getResult();
        return $tabUser;
    }
    
    
    
    

    
}

 
