<?php

namespace CoursBundle\Repository;

/**
 * AnneeEtudeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnneeEtudeRepository extends \Doctrine\ORM\EntityRepository
{
}
