<?php

namespace CoursBundle\Repository;


/**
 * CoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 */
class CoursRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCours($formation, $anneeEtude, $module, $date, $tri, $deplacement){
        
        $gestionnaireEntite=$this->_em;
        
    
        if (strcmp($tri, "Du + cher au - cher") == 0)
        {
            if (strcmp($deplacement, "accueille") == 0)
            {
                $requete=$gestionnaireEntite->createQuery('SELECT c FROM CoursBundle:Cours c JOIN c.formations f JOIN c.modules m JOIN c.anneeEtudes a WHERE c.date = :date AND f.nom = :formation AND m.nom = :module AND a.nom = :anneeEtude AND c.accueille = :accueille ORDER BY c.prix DESC');
                $requete->setParameter('formation', $formation);
                $requete->setParameter('anneeEtude', $anneeEtude);
                $requete->setParameter('module', $module);
                $requete->setParameter('date', $date);
                $requete->setParameter('accueille', 1);
                $tabFormation = $requete->getResult();
                return $tabFormation;
            }/*
            if (strcmp($deplacement, "Se déplace") == 0)
            {
                $requete=$gestionnaireEntite->createQuery('SELECT c FROM CoursBundle:Cours c JOIN c.formations f JOIN c.modules m JOIN c.anneeEtudes a WHERE c.date = :date AND f.nom = :formation AND m.nom = :module AND a.nom = :anneeEtude AND c.deplacement = :deplacement ORDER BY c.prix');
                $requete->setParameter('formation', $formation);
                $requete->setParameter('anneeEtude', $anneeEtude);
                $requete->setParameter('module', $module);
                $requete->setParameter('date', $date);
                $requete->setParameter('deplacement', 1)
                $tabFormation = $requete->getResult();
                return $tabFormation;
            }
             if (strcmp($deplacement, "Les deux") == 0)
            {
                $requete=$gestionnaireEntite->createQuery('SELECT c FROM CoursBundle:Cours c JOIN c.formations f JOIN c.modules m JOIN c.anneeEtudes a WHERE c.date = :date AND f.nom = :formation AND m.nom = :module AND a.nom = :anneeEtude AND c.deplacement = :deplacement AND c.accueil = :accueil ORDER BY c.prix');
                $requete->setParameter('formation', $formation);
                $requete->setParameter('anneeEtude', $anneeEtude);
                $requete->setParameter('module', $module);
                $requete->setParameter('date', $date);
                $requete->setParameter('deplacement', 1)
                $requete->setParameter('accueil', 1)
                $tabFormation = $requete->getResult();
                return $tabFormation;
            }*/
            else 
            {
                $requete=$gestionnaireEntite->createQuery('SELECT c FROM CoursBundle:Cours c JOIN c.formations f JOIN c.modules m JOIN c.anneeEtudes a WHERE c.date = :date AND f.nom = :formation AND m.nom = :module AND a.nom = :anneeEtude ORDER BY c.prix DESC');
                $requete->setParameter('formation', $formation);
                $requete->setParameter('anneeEtude', $anneeEtude);
                $requete->setParameter('module', $module);
                $requete->setParameter('date', $date);
                $tabFormation = $requete->getResult();
                return $tabFormation;
            }

        }
        else
        {
             if (strcmp($deplacement, "accueille") == 0)
            {
                $requete=$gestionnaireEntite->createQuery('SELECT c FROM CoursBundle:Cours c JOIN c.formations f JOIN c.modules m JOIN c.anneeEtudes a WHERE c.date = :date AND f.nom = :formation AND m.nom = :module AND a.nom = :anneeEtude AND c.accueille = :accueille ORDER BY c.prix');
                $requete->setParameter('formation', $formation);
                $requete->setParameter('anneeEtude', $anneeEtude);
                $requete->setParameter('module', $module);
                $requete->setParameter('date', $date);
                $requete->setParameter('accueille', 1);
                $tabFormation = $requete->getResult();
                return $tabFormation;
            }/*
            if (strcmp($deplacement, "Se déplace") == 0)
            {
                $requete=$gestionnaireEntite->createQuery('SELECT c FROM CoursBundle:Cours c JOIN c.formations f JOIN c.modules m JOIN c.anneeEtudes a WHERE c.date = :date AND f.nom = :formation AND m.nom = :module AND a.nom = :anneeEtude AND c.deplacement = :deplacement ORDER BY c.prix');
                $requete->setParameter('formation', $formation);
                $requete->setParameter('anneeEtude', $anneeEtude);
                $requete->setParameter('module', $module);
                $requete->setParameter('date', $date);
                $requete->setParameter('deplacement', 1)
                $tabFormation = $requete->getResult();
                return $tabFormation;
            }
             if (strcmp($deplacement, "Les deux") == 0)
            {
                $requete=$gestionnaireEntite->createQuery('SELECT c FROM CoursBundle:Cours c JOIN c.formations f JOIN c.modules m JOIN c.anneeEtudes a WHERE c.date = :date AND f.nom = :formation AND m.nom = :module AND a.nom = :anneeEtude AND c.deplacement = :deplacement AND c.accueil = :accueil ORDER BY c.prix');
                $requete->setParameter('formation', $formation);
                $requete->setParameter('anneeEtude', $anneeEtude);
                $requete->setParameter('module', $module);
                $requete->setParameter('date', $date);
                $requete->setParameter('deplacement', 1)
                $requete->setParameter('accueil', 1)
                $tabFormation = $requete->getResult();
                return $tabFormation;
            }*/
            else 
            {
                $requete=$gestionnaireEntite->createQuery('SELECT c FROM CoursBundle:Cours c JOIN c.formations f JOIN c.modules m JOIN c.anneeEtudes a WHERE c.date = :date AND f.nom = :formation AND m.nom = :module AND a.nom = :anneeEtude ORDER BY c.prix');
                $requete->setParameter('formation', $formation);
                $requete->setParameter('anneeEtude', $anneeEtude);
                $requete->setParameter('module', $module);
                $requete->setParameter('date', $date);
                $tabFormation = $requete->getResult();
                 return $tabFormation;
            }

        }
  }
        

/*
'SELECT c 
FROM CoursBundle:Cours c
JOIN c.formations f
JOIN c.modules m
JOIN c.anneeEtudes a
WHERE c.date = :date
AND f.nom = :formation
AND m.nom = :module
AND a.nom = :anneeEtude'
*/

    public function getCoursFormateurDuUser($id) {
        
       // Récupération du gestionnaire d'entité
       $gestionnaireEntite = $this->_em;

        
        $requete = $gestionnaireEntite->createQuery('SELECT c FROM CoursBundle:Cours c WHERE c.formateurs = :idFormateur');
        $requete->setParameter('idFormateur', $id);
        
        
        $cours = $requete->getResult();
        return $cours;
    }
    
    public function getCoursEleveDuUser($id) {
        
       // Récupération du gestionnaire d'entité
       $gestionnaireEntite = $this->_em;

        
        $requete = $gestionnaireEntite->createQuery('SELECT p FROM CoursBundle:Participer p JOIN p.coursP c WHERE p.utilisateurP = :idEleve');
        $requete->setParameter('idEleve', $id);
        
        
        $cours = $requete->getResult();
        
        
        return $cours;
    }

}